name: compile-pdf
on: 
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shuaibmunshi/texlive-docker
      options: -v /github/workspace:/data
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # ref: development
          token: ${{ secrets.RESUME_TOKEN }}
      # - name: Remove old PNG
      #   run: git rm images/ShuaibMunshiResume-*
      - name: Compile Latex
        run: |
          pwd
          ls -la
          xelatex ShuaibMunshiResume.tex
      - name: Check output of compile
        run: |
          ls -la images
      # - name: RM the old png before re-generating it
      #   run: rm images/ShuaibMunshiResume*.png
      - name: Generate png
        run: pdftoppm -r 300 -png ShuaibMunshiResume.pdf images/ShuaibMunshiResume
      - name: Commit PDF
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: 'Auto commit from github action'
          author_name: github_actions
          # push: origin main --force
          # push: ${{ github.ref }}
          push: origin development:main --force
        env:
            GITHUB_TOKEN: ${{ secrets.RESUME_TOKEN }}
        # run: |
        #   git config --global user.name 'Github Actions'
        #   git config --global user.email 'githubactions@users.noreply.github.com'
        #   git commit -am "Automated report"