name: compile-pdf
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shuaibmunshi/texlive-docker
      options: -v /workspace:/data
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile Latex
        run: |
          pwd
          ls -la
          ls -la
          xelatex ShuaibMunshiResume.tex
      - name: Commit PDF
        uses: EndBug/add-and-commit@v7.0.0
        with:
          default_author: github_actions
      # - name: switching from HTTPS to SSH
      #   run: git remote set-url origin ssh://git@github.com/shuaibmunshi/resume
      # - name: check for changes
      #   run: git status
      # - name: stage changed files
      #   run: git add .
      # - name: commit changed files
      #   run: git commit -m "Auto updating ShuaibMunshiResume.pdf"
      # - name: fetch from main
      #   run: git fetch origin main
      # - name: push code to main
      #   run: git push origin HEAD:main
