name: compile-pdf
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shuaibmunshi/texlive-docker
      options: -v /workspace:/data
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.RESUME_TOKEN }}
      - name: Compile Latex
        run: |
          pwd
          ls -la
          xelatex ShuaibMunshiResume.tex
      - name: Check output of compile
        run: |
          ls -la
      # - name: Commit updated PDF
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Auto commit from github action
      - name: Commit PDF
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: 'Auto commit from github action'
          default_author: github_actions
          push: true
        env:
            GITHUB_TOKEN: ${{ github.token }}


