name: compile-pdf
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shuaibmunshi/texlive-docker
      options: -v /workspace:/data
    steps:
      - name: Compile Latex
        run: xetex /data/ShuaibMunshiResume.tex
      - name: Commit pdf
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Shuaib Munshi
          author_email: munshi.shuaib@gmail.com
          message: 'Committing the compiled pdf from inside docker'
